[package]
name = "sdl-mixer-sys"
version = "0.1.5+3.2.4-72a81869b45e249e8e67102db4e98dd2441f05a1"
edition = "2024"
description = "Alternative bindings for SDL3_mixer using bindgen"
repository = "https://github.com/achusbyr/sdl-sys-rs"
license = "Zlib"
links = "SDL3_mixer"
categories = ["external-ffi-bindings"]
keywords = ["sdl", "ffi", "mixer", "audio"]

[features]
build-from-source = ["sdl-build-helper/build-from-source"]
use-pkg-config = ["sdl-build-helper/use-pkg-config"]
use-vcpkg = ["sdl-build-helper/use-vcpkg"]
link-static = []

[dependencies]
sdl-sys-bindgen = { path = "../sdl-sys-bindgen", version = "0.1" }

[build-dependencies]
sdl-build-helper = { path = "../sdl-build-helper", version = "0.1" }
