[package]
name = "sdl-main-wrapper"
version = "0.1.2"
edition = "2024"
rust-version = "1.89"
description = "Wrapper over SDL's callback-based app loop"
repository = "https://github.com/achusbyr/sdl-sys-rs"
license = "Zlib"
categories = ["api-bindings"]
keywords = ["sdl", "wrapper"]

[features]
default = ["alloc"]
alloc = []

[dependencies]
sdl-sys-bindgen = { path = "../bindings/sdl-sys-bindgen", version = "0.1" }
